services:
  - type: web
    name: syncscript-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: .next
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
